### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/4GL-npp-plugin#1]
- [ ] ecrire wiki sur les outils npp pour progress
- [ ] faire le toggle comments
- [ ] coder le beautify
- [ ] gerer le change log
- [ ] faire un ecran de gestion des bugs avec les fichiers pris en workout correspondant à l'INC et tte les infos de mes notes
- [ ] rajouter des dossiers dans le PROPATH pour aussi trouver les écrans
- [ ] faire nouveau .p, nouvelle procédure, nouvelle fonction etc...
- [ ] auto-completion des champs de tables lors de l'input "." (use P:\outils\ProgressAssist\DBReports)
- [ ] Rajouter des annotations lors du check synthax!!!!
- [ ] Faire la compilation  de tous les fichiers ouverts dans npp
- [ ] Remplacer le tab standard par des espaces
- [ ] Mettre une option pour décider si espace et/ou tab trigger un snippet
- [ ] Faire des stats users
- [ ] Faire une màj auto
- [ ] Faire une lst propre
- [ ] Faire un "go to definition" qui soit ouvre .i, .p,.w et/ou va direct à la définition de la procédure/dynamic-function(
- [ ] Faire un system de ranking pour les keyword/snippets pour afficher dans l'ordre des plus utilisé lorsqu'il y a égalité sur la contenance de la chaine "hint"
- [ ] Completion apres " :", on peut direct inserer le return return END.
- [ ] Completion des noms de table apres "gb_" et "lb_"
- [ ] Pour les keywords, on stocke le nombre d'insertion et on tri dans le Keys()
- [ ] Pour les tables/fields on a un int que l'on increment à chaque insert et on garde ainsi l'historique d'insertion
- [ ] Faire un truc pour fin de first of..
- [ ] Réduire la taille de texte  à analyser pour le keyword on left
- [ ] Pour les .lst, essayer d'abord d'ouvrir celui présent à côté du .r, si il est daté du même moment que le .r à + ou - 2s près
- [ ] Faire de l'autocompletion sur les champs des TT
- [ ] Pour le tags modif edit, reprendre également les dernière infos rentrées
- [ ] Faire le truc de cyril, filtrer les keywords par catégories à la resharper
- [ ] Nouvelles catégories : BUFFER, TEMP-TABLE, VARIABL
- [ ] Fermer le autocompleteform on page scroll
- [ ] Faire poper un menu special aux touches ALT+GR > keys.rmenu

**Comment by jcaillon** [comment]
- [ ] ne pas oublier de delete les anciens .p lors d'une update!
- [ ] ajouter un mode qui remplace les noms des tables et des fields par leur decription dans une annotation : FIND FIRST "donnees annuelles" where "annee exercice" = 2015...
- [ ] pour le parse, for each line { stocker un dico <int (n°ligne), Tuple<depth (pour indent), scope (glob, fct, proc)> // Autre dico pour buffer par exemple : <buffername, scope>? }

**Comment by jcaillon** [comment]
Pour les snippets
close on :
 * SCN_MODIFIED, modificationType = SC_PERFORMED_UNDO
* update caret selection
* tout ce qui close un autocomplete form

**Comment by jcaillon** [comment]
Loop through processes :

```csharp
        string title = "sac";
        int procID = 0;
        IntPtr fu = IntPtr.Zero;

        Process[] processlist = Process.GetProcesses();
        foreach (Process process in processlist)
        {
            if (process.MainWindowTitle.Contains(title)) {
                procID = process.Id;
                MessageBox.Show("This is the process ID: " + process.Id.ToString());
            }
        }
```

**Comment by jcaillon** [comment]
```csharp
    public override void Run()
    {
        // measure exec time
        var watch = Stopwatch.StartNew();
    
        Encoding fileEnc = Encoding.Default;
        StringBuilder strBuilder = new StringBuilder();
        
        string serverLogPath = @"P:\appli\boi1\log\server.log"; // args[0]
        
        // copy server file locally (otherwise it takes so much time to analyse)
        string localPath =  @"d:\Profiles\jcaillon\Desktop\";
        string localServerLogPath = Path.Combine(localPath, Path.GetFileName(serverLogPath));
        File.Copy(serverLogPath, localServerLogPath, true); 
        
        /*
        using(var file = new StreamReader(filePath))
        {
            while((line = file.ReadLine()) != null)
             {
                 //do something.
             }
        }
        */
        int lastTracer = 1;
        int lineNumber = 1;
        foreach (var line in File.ReadAllLines(localServerLogPath, fileEnc)) {
        
            // filter line that are exclusivly useful to the BOI
            // using this regex takes too long :
            if (Regex.IsMatch(line, @"(?:(?: - b(?:s|x)00)|(?:^.*4GLTRACE[\s]*Func (?:fi_log|bt)))", RegexOptions.IgnoreCase) && !line.Contains("error")) continue;
        
            var matches = Regex.Matches(line, @"^\[[^@]*@([^\.]*).*4GLTRACE[\s]*(.*)", RegexOptions.IgnoreCase);
            if (matches.Count > 0) {
                // we got rid of unimportant thing
                string filtererdline = matches[0].Groups[2].Value;
                
                // extract 1(func|run) 2(function called) 3(arguments) [4(calling function) - 5(calling program) @ 6(line)]
                var matches2 = Regex.Matches(filtererdline, @"^(Func|Run) ([\S]*) ([^\[]*)\[((?:(?:\w[\w-]*)\s){1,})- ([\S]*) @ ([^\]]*)\]$", RegexOptions.IgnoreCase);
                if (matches2.Count > 0) {
                    // @16:29 > ftappeltiersiv10.p (line 1, pi_appel_service) Run lireFonction3 in TiersiV1 
                    strBuilder.AppendLine("@" + matches[0].Groups[1].Value.Substring(0, 5) + " > " + matches2[0].Groups[5].Value + " (line " + matches2[0].Groups[6].Value + ", " + matches2[0].Groups[4].Value.Trim() + ") " + matches2[0].Groups[1].Value + " " +  matches2[0].Groups[2].Value + " " + matches2[0].Groups[3].Value);
                } else {
                    if (filtererdline.Length < 5) continue;
                    strBuilder.AppendLine("@" + matches[0].Groups[1].Value.Substring(0, 5) + " **" + filtererdline + "**");
                }
                
                // to find the last line containing the jcaLogTracer:
                if (matches[0].Groups[2].Value.Contains("jcaLogTracer:")) lastTracer = lineNumber;
                lineNumber += 1;
            }
        }
        
        // time it
        watch.Stop();
        MessageBox.Show(watch.ElapsedMilliseconds.ToString());
        
        // measure exec time
        watch = Stopwatch.StartNew();
        
        string outputlogPath = localServerLogPath + "~filtered.loog";
        File.WriteAllText(outputlogPath, strBuilder.ToString(), fileEnc);
        
        // time it
        watch.Stop();
        MessageBox.Show(watch.ElapsedMilliseconds.ToString());
        
        // open in npp
        OpenToNpp(outputlogPath, lastTracer);
    }
    
    public void OpenToNpp(string currentFile, int toLine)
    {
        // should be in config :
        string registryPath = @"HKEY_CURRENT_USER\Software\NppTool\";
        string nppexe = (string)Registry.GetValue(registryPath, "notepadPath", RegistryValueKind.String);

        // execute
        System.Diagnostics.Process process = new System.Diagnostics.Process();
        process.StartInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
        process.StartInfo.CreateNoWindow = true;
        process.StartInfo.FileName = nppexe;
        process.StartInfo.Arguments = " -n" + toLine.ToString() + " " + quoter(currentFile);
        process.Start();
    }
    
    private string quoter(string inString) {
        return "\"" + inString + "\"";
    }
```

**Comment by jcaillon** [comment]
```csharp
using NppScripts;
using System;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Xml;
using System.Web.Script.Serialization;
using System.Text.RegularExpressions;
using System.Linq;
using Microsoft.Win32;

public class Script : NppScript
{
    public override void Run()
    {   
        var watch = Stopwatch.StartNew();
        StringBuilder output = new StringBuilder();
   
        MatchCollection matches;
        
        // we take the whole text of the document, then we want to strip stuff out before we parse it; including : comments and strings!
        string wholeDocumentText = Npp.GetAllText();
        string documentText = wholeDocumentText.StripAllStrings();
        documentText = documentText.StripAllComments();
        
        // we take everything, and then we will filter (it can not start with "scoped-"define
        // (?:^|[^-])DEF(?:INE)?\s
        // (?:DEFINE|DEF)\s
        string commonStartRegex = @"DEF(?:INE)?\s";
        
        
        #region buffers
        // - 1 { [ [ NEW ] SHARED ] | [ PRIVATE | PROTECTED ] [ STATIC ] }
        // - 2 name of the buffer
        // - 3 TEMP-TABLE (or empty)
        // - 4 table-name
        // - 5 rest of the decla
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)BUFFER\s+([\w-]+)\s+FOR\s+(TEMP-TABLE)?\s*([\w-]+)([^\w\.]*[^.]*)\.", RegexOptions.IgnoreCase);
        output.AppendLine("BUFFERS : " + matches.Count.ToString() + " ");

        /*
        var i = 0;
        foreach (Match match in matches) {
            if (i == 0 && (match.Groups[1].Value.Length > 1)) {
                //MessageBox.Show(match.Value);
                //MessageBox.Show(match.Groups[1].Value + "\n" + match.Groups[2].Value + "\n" + match.Groups[3].Value + "\n" + match.Groups[4].Value + "\n" + match.Groups[5].Value);
                i++;
            }
        }
        */
        #endregion
        
        #region variables
        // - 1 { [ [ NEW [ GLOBAL ] ] SHARED ] | [ PRIVATE | PROTECTED | PUBLIC ] [ STATIC ] }
        // - 2 name of the variable
        // - 3 (AS captures until the dot) 
        //    - 4 is the class
        //    - 5 is the rest of the declar
        // or 
        // - 3 (LIKE captures until the dot)
        //    - 6 is the variable/fields "like"
        //    - 7 is the rest of the decla
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)(?:VARIABLE|VAR)\s+([\w-]+)\s+(AS\s+([A-Z-]{2,})([^.]*)\.|LIKE\s+([\w]+\.[\w]+\.[\w]+|[\w]+\.[\w]+|[\w-]+)([^.]*)\.)", RegexOptions.IgnoreCase);
        output.AppendLine("VARIABLES : " + matches.Count.ToString() + " ");

        // if there is a "VIEW-AS " in the rest of the declaration, it means the variables is shown on screen
        
        /*
        i = 0;
        foreach (Match match in matches) {
            if (i == 0 && (match.Groups[3].Value.StartsWith("LIKE"))) {
                MessageBox.Show(match.Value + " @ " + match.Index);
                MessageBox.Show(match.Groups[1].Value + "\n" + match.Groups[2].Value + "\n" + match.Groups[3].Value + "\n" + match.Groups[4].Value + "\n" + match.Groups[5].Value + "\n" + match.Groups[6].Value + "\n" + match.Groups[7].Value);
                i++;
            }
        }
        */
        #endregion
        
        #region temp-tables        
        // - 1 { [ [ NEW [ GLOBAL ] ] SHARED ] | [ PRIVATE | PROTECTED ] [ STATIC ] }
        // - 2 name of the tt
        // - 3 rest of the decla
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)(?:TEMP-TABLE|WORKFILE|WORK-TABLE)\s+([\w-]+)\s+(([^.]|\.(?!\s))*)\.", RegexOptions.IgnoreCase);
        output.AppendLine("TEMP-TABLES : " + matches.Count.ToString() + " ");
        //MessageBox.Show(matches[0].Groups[1].Value + "\n" + matches[0].Groups[2].Value + "\n" + matches[0].Groups[3].Value);
        /*
        i = 0;
        foreach (Match match in matches) {
            if (i == 0) {
                MessageBox.Show(match.Groups[2].Value + "\n@ char pos :" + match.Index + " @ line :" + documentText.GetLineFromCharPos(match.Index).ToString());
                MessageBox.Show(match.Groups[1].Value + "\n" + match.Groups[2].Value + "\n" + match.Groups[3].Value);
                i++;
            }
        }
        */
        #endregion
        
        #region stream
        // - 1 { [ [ NEW [ GLOBAL ] ] SHARED ] | [ PRIVATE ] }
        // - 2 name of the stream
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)STREAM\s+([\w-]+)\.", RegexOptions.IgnoreCase);
        output.AppendLine("STREAMS : " + matches.Count.ToString() + " ");
        #endregion
        
        #region browse
        // DEF(?:INE)?\s([\w\s]*)BROWSE\s+([\w-]+)\s+(([^.]|\.(?!\s))*)\.
        // (?        s([\w\s]*)BROWSE\s+([\w-]+)\s+([^.]*)\.
        // - 1 { [ [ NEW ] SHARED ] | [ PRIVATE ] }
        // - 2 name of the browse
        // - 3 rest
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)BROWSE\s+([\w-]+)\s+(([^.]|\.(?!\s))*)\.", RegexOptions.IgnoreCase);
        output.AppendLine("BROWSE : " + matches.Count.ToString() + " " );
        #endregion
        
        #region button
        // - 1 [ PRIVATE ]
        // - 2 name of the button
        // - 3 rest
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)BUTTON\s+([\w-]+)\s+([^.]*)", RegexOptions.IgnoreCase);
        output.AppendLine("BUTTON : " + matches.Count.ToString() + " ");
        #endregion
        
        #region dataset
        // - 1 { [ [ NEW ] SHARED ] | [ PRIVATE | PROTECTED ] [ STATIC ] }
        // - 2 name of the dataset
        // - 3 rest
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)DATASET\s+([\w-]+)\s+([^.]*)", RegexOptions.IgnoreCase);
        output.AppendLine("DATASET : " + matches.Count.ToString() + " ");
        #endregion
        
        #region frame
        // - 1 { [ [ NEW ] SHARED ] | [ PRIVATE ] }
        // - 2 name of the frame
        // - 3 rest
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)FRAME\s+([\w-]+)\s+([^.]*)", RegexOptions.IgnoreCase);
        output.AppendLine("FRAME : " + matches.Count.ToString() + " ");
        #endregion
        
        #region query
        // - 1 { [ [ NEW ] SHARED ] | [ PRIVATE | PROTECTED ] [ STATIC ] }
        // - 2 name of the query
        // - 3 buffer name
        // - 4 rest
        matches = Regex.Matches(documentText, commonStartRegex + @"([\w\s]*)QUERY\s+([\w-]+)\s+FOR\s+([\w,-]+)\s+([^.]*)", RegexOptions.IgnoreCase);
        output.AppendLine("QUERY : " + matches.Count.ToString() + " ");
        #endregion
        
        #region rectangle
        // - 1 name of the rectangle
        matches = Regex.Matches(documentText, commonStartRegex + @"+(?:PRIVATE\s)?\s*RECTANGLE\s+([\w-]+)\s+[^.]*\.", RegexOptions.IgnoreCase);
        output.AppendLine("RECTANGLE : " + matches.Count.ToString() + " ");
        #endregion
        
        #region &scoped-define
        // - 1 name of the variable
        // - 2 string definition
        matches = Regex.Matches(documentText, @"&SCOPED-DEFINE\s+([\w-]+)\s(.*?)\n", RegexOptions.IgnoreCase);
        output.AppendLine("&SCOPED-DEFINE : " + matches.Count.ToString() + " ");
        #endregion
        
        #region &global-define
        // - 1 name of the variable
        // - 2 string definition
        matches = Regex.Matches(documentText, @"&GLOBAL-DEFINE\s+([\w-]+)\s(.*?)\n", RegexOptions.IgnoreCase);
        output.AppendLine("&GLOBAL-DEFINE : " + matches.Count.ToString() + " ");
        #endregion
        
        #region &undefine
        // - 1 name of the variable
        matches = Regex.Matches(documentText, @"&UNDEFINE\s+([\w-]+)", RegexOptions.IgnoreCase);
        output.AppendLine("&UNDEFINE : " + matches.Count.ToString() + " ");
        #endregion
        
        // missing :
        // - DEFINE DATA-SOURCE
        // - DEFINE EVENT
        // - DEFINE IMAGE
        // - DEFINE MENU
        // - DEFINE PROPERTY
        // - DEFINE SUB-MENU
        
        // results
        watch.Stop();
        MessageBox.Show(output.ToString() + "\nin " + watch.ElapsedMilliseconds.ToString() + " ms");
        
        /*
        watch = Stopwatch.StartNew();
        for (var y = 0; y < 999; y++) {
            wholeDocumentText.GetLineFromCharPos((int)Win32.SendMessage(Npp.CurrentScintilla, SciMsg.SCI_GETCURRENTPOS, 0, 0));
        }
        watch.Stop();
        MessageBox.Show(watch.ElapsedMilliseconds.ToString() + " ms" + "\n" + wholeDocumentText.GetLineFromCharPos((int)Win32.SendMessage(Npp.CurrentScintilla, SciMsg.SCI_GETCURRENTPOS, 0, 0)).ToString());
        */
        
        // test if the current position is in a comment :
        //var pos = (int)Win32.SendMessage(Npp.CurrentScintilla, SciMsg.SCI_GETCURRENTPOS, 0, 0);        
        //MessageBox.Show("pos = " + pos.ToString() + ", coment nesting = " + Npp.GetAllText().GetCommentNestingLevel(pos).ToString());
    }
}

public static class StringExt {
    
    public static int GetLineFromCharPos(this string str, int pos) {
        return str.Substring(0, pos).CountOccurences("\n") + 1;
    }
    
    public static string StripAllComments(this string str) {
        // can remove the deepest level of nested comment, called recursivly to remove them all
        string retStr =  Regex.Replace(str, "/\\*([^\\*])*\\*/", "");
        return (str.Length != retStr.Length) ? retStr.StripAllComments() : retStr;
    }
    
    public static string StripAllStrings(this string str) {
        // returns the string without all the strings defined by 2 simple or double quotes
        return Regex.Replace(Regex.Replace(str, "\"[^\"\n]*\"", ""), "'[^'\n]*'", "");
    }
    
    public static int GetCommentNestingLevel(this string str, int pos) {
        // we must first get rid of all the string because they can potentially contain /* or */
        string retStr = str.Substring(0, pos).StripAllStrings();
        return retStr.CountOccurences("/*") - retStr.CountOccurences("*/");
    }
    
    public static int CountOccurences(this string haystack, string needle) {
        return (haystack.Length - haystack.Replace(needle, "").Length) / needle.Length;
    }
    
    public static IEnumerable<string> FilterFiles(string path, params string[] exts) {
        return exts.Select(x => "*." + x) // turn into globs
            .SelectMany(x => Directory.EnumerateFiles(path, x));
    }
}
```
